### ISSUE TITLE
Need LiveDuel app icon for facebook app.

### ISSUE THREAD

**Issue by ispyhumanfly** [thoughtpivot/liveduel#12]
1024 x 1024. 

100x100

**Comment by willpmartin** [comment]
@ispyhumanfly here is a link to the icon in the file sizes requested. 

I have also uploaded the other artwork/graphics related to the project. 

https://drive.google.com/drive/folders/1F8Bj2M0UvKDaygedU5aRs_qo85WgL1kE?usp=sharing
